name: Run Docker-Based Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci
      - name: Pull required Docker images
        run: |
          docker pull --platform=linux/amd64 node:lts-slim
          docker pull --platform=linux/amd64 mcr.microsoft.com/playwright:v1.52.0-noble
          docker pull --platform=linux/amd64 alfonsograziano/node-code-sandbox-mcp:latest

      - name: Run tests
        run: npm test
